---

- name: assert missing or wrong java version
  assert:
    that:
      - java_version is defined
      - java_version in java_supported_versions
    msg: "wrong java_version: '{{ java_version }}'. Supported versions are: {{ java_supported_versions }}"
    quiet: true

- name: define java full version
  set_fact:
    java_full_version: "{{ java_version_map[java_version] | java_full_version(java_jvm, 'linux', os_arch) }}"
    java_release_version: "{{ java_version_map[java_version] | java_release_version(java_jvm, 'linux', os_arch) }}"
    java_file: "{{ java_version_map[java_version] | basename }}"

- name: define java download file
  set_fact:
    java_download_file: "{{ java_download.url }}/temurin{{ java_version }}-binaries/releases/download/jdk-{{ java_release_version }}/{{ java_file }}"

- block:
    - name: get checksum list
      set_fact:
        __java_checksums: "{{ lookup('url', java_download_file  + '.sha256.txt', wantlist=True) | list }}"
      run_once: true

    - name: get checksum for {{ os_arch }} architecture
      set_fact:
        __java_checksum: "{{ __java_checksums | java_checksum('linux', os_arch) }}"
  delegate_to: localhost

- name: fetch java {{ java_version }} from download-server {{ java_download.url }}
  become: false
  delegate_to: "{{ java_delegate_to }}"
  get_url:
    url: "{{ java_download_file }}"
    dest: "{{ java_local_tmp_directory }}/{{ java_file }}"
    # timeout: 320
    url_username: "{{ java_download.username | default(omit) }}"
    url_password: "{{ java_download.password | default(omit) }}"
    checksum: "sha256:{{ __java_checksum }}"
  no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 2
  delay: 2

...
