---

- name: detect docker environment
  set_fact:
    is_docker_guest: "{{
      ansible_virtualization_role | default('host') == 'guest' and
      ansible_virtualization_type | default('none') == 'docker' }}"

- name: define list of supported java versions
  set_fact:
    java_supported_versions: "{{ java_version_map | flatten | sort }}"

- name: update package cache
  package:
    update_cache: true

- name: define delegate instance for download handling
  set_fact:
    java_delegate_to: "{{ ansible_host }}"
    java_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/java', true) }}/{{ java_version }}"
  when:
    - java_direct_download

- name: install dependencies
  package:
    name: "{{ java_dependencies }}"
    state: present

- name: gathering facts now
  setup:

- name: create download directory
  become: false
  delegate_to: "{{ java_delegate_to }}"
  file:
    path: "{{ java_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: create install directory
  file:
    state: directory
    path: "{{ java_install_directory }}"
    mode: 0750

- name: create ansible local facts directory
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775

...
