---
name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 0"

defaults:
  run:
    working-directory: 'ansible-multi-java'

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  arch:
    name: "${{ matrix.image }} / ansible ${{ matrix.ansible-version }} / python ${{ matrix.python }}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux:latest
        python_version:
          - "3.11"
          - "3.12"
        ansible-version:
          - '8.5'

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'ansible-multi-java'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: force reinstall of community.docker
        run: |
          mkdir -p /home/runner/.ansible/collections
          ansible-galaxy collection install community.docker --force

      # # See: https://github.com/geerlingguy/ansible-role-mysql/issues/422
      # - name: Disable AppArmor
      #   run: |
      #       set -x
      #       sudo apt-get install apparmor-profiles
      #       sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      #       sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

      - name: test with tox
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"
